export const tokenList = [
  {
    id: 1,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 1,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 2,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 2,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 3,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 0,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 4,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 3,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
  {
    id: 5,
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
];
