export const tokenList = [
  {
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 1,
    tokenReward: "ETH",
    logo: "",
  },
  {
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 2,
    tokenReward: "ETH",
    logo: "",
  },
  {
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 0,
    tokenReward: "ETH",
    logo: "",
  },
  {
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 3,
    tokenReward: "ETH",
    logo: "",
  },
  {
    name: "Tether USD",
    symbol: "TUSD",
    totalSupply: 14722,
    reward: 4,
    tokenReward: "ETH",
    logo: "",
  },
];
