import "../styles/app.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import DebugGrid from "@/components/DebugGrid";
import { chakraPetch } from "@/constants/fonts";
import { BlastThemeProvider } from "@/contexts/BlastThemeProvider";
import Header from "@/layouts/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en">
      <body className={`${inter.className} ${chakraPetch.className}`}>
        <BlastThemeProvider cookies={"blasttheme"}>
          <DebugGrid />
          <Header />
          {children}
        </BlastThemeProvider>
      </body>
    </html>
  );
}
