import "../styles/app.scss";

import type { Metadata } from "next";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

import DebugGrid from "@/components/DebugGrid";
import { chakraPetch } from "@/constants/fonts";
import Header from "@/layouts/Header";
import { config } from "@/wagmi/config";

import Providers from "./providers";
// import Template from "./template";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  const initialState = cookieToInitialState(config, headers().get("cookie"))!;
  return (
    <html lang="en">
      <body className={` ${chakraPetch.className}`}>
        <Providers initialState={initialState}>
          <Header />
          <DebugGrid />
          {children}
        </Providers>
      </body>
    </html>
  );
}
